### ISSUE TITLE
Plugin adoption?

### ISSUE THREAD

**Issue by ethanclevenger91** [quesihealy/cf7-pipedrive#11]
Hey @quesihealy - saw this plugin was closed on the wp.org repo per your request. Any chance you're interested in handing off support?

**Comment by quesihealy** [comment]
Happy to @ethanclevenger91! I don't have the bandwidth my-self. You're welcome to use the repo here to open a plugin. I was told by closing out the repo it's closed for good and can't be reopened. Thank you! Let me know if I can somehow help.

**Comment by ethanclevenger91** [comment]
@quesihealy if you want to add me as a collaborator on this repo, I'm happy to at least maintain it here. I see an open PR that could be worth reviewing, for example.

**Comment by quesihealy** [comment]
Thank you for taking that on @ethanclevenger91. I've added you as a collaborator. Let me know if anything else comes up.

**Comment by ethanclevenger91** [comment]
@quesihealy Sorry I didn't realize that was an invitation I had to accept and it expired >.<

Send along again and I'll be prompt about it

**Comment by quesihealy** [comment]
No Worries. Sent another invite.
