### ISSUE TITLE
Contact Form 7 Fields empty

### ISSUE THREAD

**Issue by maartenhemmes** [quesihealy/cf7-pipedrive#2]
Hi, I have set-up the plugin and I'm trying to select fields but regardless from which contact form I select, the dropdown remains empty. 

Any advise?
<img width="525" alt="screen shot 2017-08-24 at 11 43 01 am" src="https://user-images.githubusercontent.com/3624039/29648564-6cbff262-88c1-11e7-91ba-3cb550ae65c3.png">

**Comment by quesihealy** [comment]
Hello,

Can I ask what version of Contact Form 7 you are using? Thank you for the feedback!

**Version 4.9 of Contact Form 7 is the earliest confirmed version to work with this plugin**

Older versions will not show the drop down menus (like in the image above)
