### ISSUE TITLE
Message

### ISSUE THREAD

**Issue by itsme100** [quesihealy/cf7-pipedrive#4]
Hi!
I stumbled upon this and it is just what I was looking for, great!
However, as I want to use it as a B2B lead generation tool too, I cannot use it without seeing in Pipedrive the message people enter into CF7.
It would be great if you could manage to show the CF7 message in a note in Pipedrive!

Thanks a lot!

**Comment by quesihealy** [comment]
I do have plans to expand options, but nothing is currently in the pipeline. I'm going to wait a month or two more for feedback/bugs on the current set-up then plan on expanding.
