### ISSUE TITLE
Get custom fields from pipedrive

### ISSUE THREAD

**Issue by kallel-anobom** [quesihealy/cf7-pipedrive#6]
Get the custom fields dynamically from the pipedrive API.

I have the code to do that, soon I will make a pull request, jut opening this issue to discuss the new feature.

**Comment by quesihealy** [comment]
This was in the Pipeline for me. If you have the code I'd love to add it to the project.

**Comment by kallel-anobom** [comment]
Hello, there was a problem with my code? Why not accept git pull?

**Comment by quesihealy** [comment]
Hello. Sorry for the delay. This isn't my full time job and unfortunately
mine has been keeping me busy. I'm sure it's fine. I plan to get around to
it this week. Thanks for the poke to get to it.

**Comment by quesihealy** [comment]
Thank you for the contribution!
